# platform = multi_platform_rhel
# reboot = false
# strategy = configure
# complexity = low
# disruption = low

{{{ ansible_instantiate_variables("rsyslog_remote_loghost_address") }}}

- name: "{{{ rule_title }}}: search for omfwd action directive in rsyslog include files"
  ansible.builtin.find:
    paths: "/etc/rsyslog.d/"
    pattern: "*.conf"
    contains: '^\s*action\s*\(\s*type\s*=\s*"omfwd".*'
  register: rsyslog_includes_with_directive

- name: "{{{ rule_title }}}: search for omfwd action directive in rsyslog main config file"
  ansible.builtin.find:
    paths: "/etc"
    pattern: "rsyslog.conf"
    contains: '^\s*action\s*\(\s*type\s*=\s*"omfwd".*'
  register: rsyslog_main_file_with_directive

- name: "{{{ rule_title }}}: assemble list of files with existing omfwd directives"
  ansible.builtin.set_fact:
    rsyslog_files: "{{ rsyslog_includes_with_directive.files | map(attribute='path') | list + rsyslog_main_file_with_directive.files | map(attribute='path') | list }}"

- name: "{{{ rule_title }}}: fix existing omfwd directives"
  when: rsyslog_includes_with_directive.matched > 0 or rsyslog_main_file_with_directive.matched > 0
  block:
    - name: "{{{ rule_title }}}: replace wrong authmode value in omfwd action"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '(?i)^(\s*action\s*\(\s*type\s*=\s*"omfwd"[\s\S]*)((?:streamdriver\.authmode|tls\.authmode|streamdriverauthmode)\s*=\s*"\S*")([\s\S]*\))$'
        replace: '\1streamdriver.authmode="x509/name"\3'
      loop: "{{ rsyslog_files }}"

    - name: "{{{ rule_title }}}: add authmode if missing from omfwd action"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '(?i)^(\s*action\s*\(\s*type\s*=\s*"omfwd"(?:(?!(?:streamdriver\.authmode|tls\.authmode|streamdriverauthmode)\s*=\s*"\S*")[\s\S])*?)(\)\s*)$'
        replace: '\1  streamdriver.authmode="x509/name"\n\2'
      loop: "{{ rsyslog_files }}"

    - name: "{{{ rule_title }}}: replace wrong permittedpeer value in omfwd action"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '(?i)^(\s*action\s*\(\s*type\s*=\s*"omfwd"[\s\S]*)((?:streamdriver\.permittedpeer|tls\.permittedpeer|streamdriverpermittedpeer)\s*=\s*"\S*")([\s\S]*\))$'
        replace: '\1streamdriver.permittedpeer="{{ rsyslog_remote_loghost_address }}"\3'
      loop: "{{ rsyslog_files }}"

    - name: "{{{ rule_title }}}: add permittedpeer if missing from omfwd action"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '(?i)^(\s*action\s*\(\s*type\s*=\s*"omfwd"(?:(?!(?:streamdriver\.permittedpeer|tls\.permittedpeer|streamdriverpermittedpeer)\s*=\s*"\S*")[\s\S])*?)(\)\s*)$'
        replace: '\1  streamdriver.permittedpeer="{{ rsyslog_remote_loghost_address }}"\n\2'
      loop: "{{ rsyslog_files }}"
