#!/usr/bin/env bash
# Writes ../ansible/inventory.ini from the current 'vagrant ssh-config' output.
# Called automatically by the Vagrantfile trigger after 'vagrant up'.
# Safe to re-run manually at any time.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INVENTORY="${SCRIPT_DIR}/../ansible/inventory.ini"

# vagrant ssh-config is relative to the Vagrantfile location
cd "$SCRIPT_DIR"

VM_HOST=$(vagrant ssh-config 2>/dev/null | awk '/^  HostName / { print $2 }')
VM_PORT=$(vagrant ssh-config 2>/dev/null | awk '/^  Port /     { print $2 }')
VM_KEY=$(vagrant ssh-config  2>/dev/null | awk '/^  IdentityFile / { print $2 }')
VM_USER=$(vagrant ssh-config 2>/dev/null | awk '/^  User /     { print $2 }')

if [[ -z "$VM_HOST" ]]; then
  echo "ERROR: Could not read VM address from 'vagrant ssh-config'. Is the VM running?" >&2
  exit 1
fi

mkdir -p "$(dirname "$INVENTORY")"

cat > "$INVENTORY" << EOF
# Auto-generated by populate_inventory.sh — do not edit manually.
# Regenerate with: cd utils/nist_sync/vagrant && bash populate_inventory.sh

[rhel9_scanner]
nist-rhel9-scanner \
  ansible_host=${VM_HOST} \
  ansible_port=${VM_PORT:-22} \
  ansible_user=${VM_USER:-vagrant} \
  ansible_ssh_private_key_file=${VM_KEY} \
  ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[rhel9_scanner:vars]
ansible_python_interpreter=/usr/bin/python3
EOF

echo "Written: ${INVENTORY}"
echo "  VM: ${VM_USER:-vagrant}@${VM_HOST}:${VM_PORT:-22}"
echo "  Key: ${VM_KEY}"
