#!/bin/bash
# Populate Ansible inventory with the running Fedora Vagrant VM's SSH details.
#
# Called automatically by the Vagrantfile after 'vagrant up',
# or manually from the vagrant/ directory.
#
# Usage:
#   bash populate_inventory_fedora.sh

set -euo pipefail

VAGRANT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ANSIBLE_DIR="$VAGRANT_DIR/../ansible"
INVENTORY_FILE="$ANSIBLE_DIR/inventory.ini"

if [[ ! -f "$VAGRANT_DIR/Vagrantfile.fedora" ]]; then
  echo "Error: Vagrantfile.fedora not found in $VAGRANT_DIR"
  exit 1
fi

# Extract SSH connection details from Vagrant
VAGRANT_VAGRANTFILE=Vagrantfile.fedora
export VAGRANT_VAGRANTFILE

SSH_HOST=$(vagrant ssh-config | grep -w HostName | awk '{print $2}')
SSH_PORT=$(vagrant ssh-config | grep -w Port | awk '{print $2}')
SSH_USER=$(vagrant ssh-config | grep -w User | awk '{print $2}')
SSH_KEY=$(vagrant ssh-config | grep -w IdentityFile | awk '{print $2}')

if [[ -z "$SSH_HOST" || -z "$SSH_PORT" ]]; then
  echo "Error: could not extract SSH details from 'vagrant ssh-config'"
  echo "       Is the VM running? Try: VAGRANT_VAGRANTFILE=Vagrantfile.fedora vagrant up"
  exit 1
fi

cat > "$INVENTORY_FILE" << EOF
# Ansible inventory for Fedora NIST scanner VM.
# Auto-generated by populate_inventory_fedora.sh — do not edit manually.

[fedora_scanner]
nist-fedora-scanner ansible_host=$SSH_HOST ansible_port=$SSH_PORT ansible_user=$SSH_USER ansible_ssh_private_key_file=$SSH_KEY ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
EOF

echo "Wrote $INVENTORY_FILE"
echo ""
echo "Next steps:"
echo "  cd $VAGRANT_DIR/.."
echo "  ansible-playbook -i ansible/inventory.ini ansible/setup_fedora.yml \\"
echo "      -e complyctl_bin=/tmp/complyctl \\"
echo "      -e provider_bin=~/.complytime/providers/complyctl-provider-openscap"
echo ""
echo "  ansible-playbook -i ansible/inventory.ini ansible/scan_fedora.yml"
