downstream_package_name: scap-security-guide
upstream_package_name: scap-security-guide
upstream_tag_template: '{version}'
specfile_path: scap-security-guide.spec

actions:
  get-current-version:
  - bash utils/version.sh

srpm_build_deps:
  - bash

jobs:
- &build
  job: copr_build
  trigger: pull_request
  targets:
  - fedora-all-x86_64
  - centos-stream-8-x86_64
  - centos-stream-9-x86_64
  - centos-stream-10-x86_64

- <<: *build
  trigger: commit
  branch: "gh-readonly-queue/.*"

# Contest-based /hardening/host-os testing
# - this is a minimal set of tests that can run directly on the reserved OS
#   by remediating + scanning it
# - let Packit handle it natively by installing built scap-security-guide RPM
#   and calling Contest to test that OS-installed RPM content

- &contest-host-os-oscap
  job: tests
  trigger: pull_request
  fmf_url: https://github.com/RHSecurityCompliance/contest.git
  fmf_ref: main
  tmt_plan: /plans/upstream-parallel/oscap
  identifier: contest-host-os-oscap
  targets:
    centos-stream-8: {}
    centos-stream-9: {}
    centos-stream-10: {}
  tf_extra_params:
    settings:
      pipeline:
        parallel-limit: 32

- <<: *contest-host-os-oscap
  tmt_plan: /plans/upstream-parallel/ansible
  identifier: contest-host-os-ansible

- <<: *contest-host-os-oscap
  tmt_plan: /plans/upstream-parallel/other
  identifier: contest-host-os-other

# Contest-based testing where the contest-atex-testingfarm is run via Packit
# on a huge VM host, setting up many containers/VMs to parallelize the testing,
# also allowing it to run tests that require VMs
# - this effectively allows full Contest suite execution (all tests that make
#   sense for PR testing here)

- job: tests
  trigger: pull_request
  fmf_url: https://github.com/RHSecurityCompliance/contest-atex-testingfarm.git
  fmf_ref: main
  identifier: contest-all
  targets: [fedora-latest-stable]
  manual_trigger: true
  skip_build: true
  tf_extra_params:
    # increase default, per README.md of the above repo
    # - this includes time spent waiting in queued
    settings:
      pipeline:
        timeout: 1200

# tests present locally in this repo, under tests/
# - when modifying these, modify also tests/tmt/

- job: tests
  trigger: pull_request
  fmf_path: tests/tmt
  tmt_plan: /fedora-cis/plan$
  identifier: fedora-cis
  targets:
    fedora-all: {}

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all
