product: bascontroltwentytwod4
full_name: Bascontroltwentytwod 4
type: product

benchmark_id: BASCONTROLTWENTYTWOD-4
benchmark_root: "./guide"

components_root: "../../components"

profiles_root: "./profiles"

cpes_root: "../../shared/applicability"
cpes:
  - bascontroltwentytwod4:
      name: "cpe:/a:bascontroltwentytwod:4"
      title: "Bascontroltwentytwod 4"
      check_id: installed_app_is_bascontroltwentytwod4
