# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_sle,multi_platform_almalinux
# reboot = false
# strategy = restrict
# complexity = low
{{{ ansible_instantiate_variables("var_accounts_password_minlen_login_defs") }}}

{{% if product in [ 'slmicro6', 'sle15', 'sle16' ] %}}
{{% set cce_cce_identifier = cce_identifiers['cce'] %}}
{{{
    ansible_login_defs(
      parameter='PASS_MIN_LEN',
      value='{{ var_accounts_password_minlen_login_defs }}',
      rule_title=rule_title,
      cce=cce_cce_identifier
    )
}}}
{{% else %}}
- name: Set Password Minimum Length
  ansible.builtin.lineinfile:
    dest: {{{ login_defs_path }}}
    regexp: ^PASS_MIN_LEN
    line: "PASS_MIN_LEN {{ var_accounts_password_minlen_login_defs }}"
    create: yes
    mode: 0644
{{% endif %}}
