---
# platform = multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
spec:
  kubeletConfig:
    evictionHard:
      nodefs.inodesFree: {{.var_kubelet_evictionhard_nodefs_inodesfree}}
    evictionPressureTransitionPeriod: 0s
