---
# platform = multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
spec:
  kubeletConfig:
    evictionHard:
      imagefs.inodesFree: {{.var_kubelet_evictionhard_imagefs_inodesfree}}
    evictionPressureTransitionPeriod: 0s
