.TH scap-security-guide 8 "26 Jan 2013" "version 1"

.SH NAME
SCAP Security Guide - Delivers security guidance, baselines, and associated
validation mechanisms utilizing the Security Content Automation Protocol
(SCAP).


.SH DESCRIPTION
The project provides practical security hardening advice for Red Hat and Fedora
products, and also links it to compliance requirements in order to ease
deployment activities, such as certification and accreditation. These include
requirements in the U.S. government (Federal, Defense, and Intelligence
Community) as well as of the financial services and health care industries. For
example, high-level and widely-accepted policies such as NIST 800-53 provides
prose stating that System Administrators must audit "privileged user actions,"
but do not define what "privileged actions" are. The SSG bridges the gap
between generalized policy requirements and specific implementation guidance,
in SCAP formats to support automation whenever possible.

The projects homepage is located at:
https://fedorahosted.org/scap-security-guide/


.SH PROFILES
The SSG content is broken into 'profiles,' groupings of security settings that
correlate to a known policy. Currently available profile:

.I common
.RS
The common profile is intended to be used as a base, universal profile for
scanning of general-purpose Fedora systems.


.SH EXAMPLES
To scan your system utilizing the OpenSCAP utility against the
common profile, run:

$ oscap  xccdf eval --profile common \
--results /tmp/`hostname`-ssg-results.xml \
--report /tmp/`hostname`-ssg-results.html \
--cpe /usr/share/xml/scap/ssg/fedora/ssg-fedora-cpe-dictionary.xml \
/usr/share/xml/scap/ssg/fedora/ssg-fedora-xccdf.xml

To scan your system utilizing the scap-workbench systems compliance evaluation
GUI tool against the common profile, run:

$ scap-workbench

tool, select /usr/share/xml/scap/ssg/fedora/ssg-fedora-xccdf.xml
as input file, and 'Common Profile for General-Purpose Fedora Systems' as the
profile file.

.PP
Additional details can be found on the projects wiki page:
https://fedorahosted.org/scap-security-guide/wiki/usageguide


.SH FILES
.I /usr/share/xml/scap/ssg/fedora/
.RS
Houses SCAP content utilizing the following naming conventions:

.I CPE_Dictionaries:
ssg-fedora-cpe-dictionary.xml

.I CPE_OVAL_Content:
ssg-fedora-cpe-oval.xml

.I OVAL_Content:
ssg-fedora-oval.xml

.I XCCDF_Content:
ssg-fedora-xccdf.xml
.RE

.I /usr/share/doc/scap-security-guide-0.1/
.RS
HTML version of SSG profile.
.RE


.SH SEE ALSO
.B oscap(8), scap-workbench(20)


.SH AUTHOR
Please direct all questions to the SSG mailing list:
https://lists.fedorahosted.org/mailman/listinfo/scap-security-guide
