---
# platform = multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
spec:
  kubeletConfig:
    evictionHard:
      memory.available: {{.var_kubelet_evictionhard_memory_available}}
    evictionPressureTransitionPeriod: 0s
