---
# platform = multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
spec:
  kubeletConfig:
    evictionSoft:
      imagefs.available: {{.var_kubelet_evictionsoft_imagefs_available}}
    evictionSoftGracePeriod:
      imagefs.available: "1m30s"
    evictionPressureTransitionPeriod: 0s
