# platform = multi_platform_all
# reboot = false
# strategy = configure
# complexity = low
# disruption = low

{{%- set files = ["bash_logout", "bash_profile", "bashrc", "cshrc", "tcshrc", ] %}}

- name: "{{{ rule_title }}} - Ensure source directory exists"
  ansible.builtin.file:
    path: /usr/share/rootfiles
    state: directory
    mode: '0755'
    owner: root
    group: root

{{%- for file in files %}}
    {{% set dest_path = "/root/." ~  file -%}}
    {{% set source_path = "/usr/share/rootfiles/." ~ file -%}}
    {{% set new_line = "C " ~ dest_path ~ " 600 root root - "  ~ source_path  %}}
- name: "{{{ rule_title }}} - Stat {{{ dest_path }}}"
  ansible.builtin.stat:
    path: "{{{ dest_path }}}"
  register: {{{ rule_id }}}_{{{ file }}}_root_stat
- name: "{{{ rule_title }}} - Copy {{{ dest_path }}} to {{{ source_path }}} if missing"
  ansible.builtin.copy:
    src: "{{{ dest_path }}}"
    dest: "{{{ source_path }}}"
    remote_src: true
    force: false
  when: {{{ rule_id }}}_{{{ file }}}_root_stat.stat.exists
- name: "{{{ rule_title }}} - Find configuration files"
  ansible.builtin.find:
    paths: /etc/tmpfiles.d/
    file_type: file
    patterns: '*.conf'
  register: {{{ rule_id }}}_{{{ file }}}_found_files
- name: "{{{ rule_title }}} - Remove existing configuration"
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: '^C\s+/root/\.{{{ file }}}.+$'
    state: absent
  loop: "{{ {{{ rule_id }}}_{{{ file }}}_found_files.files }}"
{{{ ansible_lineinfile(msg='', path='/etc/tmpfiles.d/rootfiles.conf', new_line=new_line, create='yes', state='present', insert_after='', insert_before='', regex=source_path, rule_title=rule_title)  -}}}
{{%- endfor %}}
