#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, ComplianceAsCode project
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
"""Ansible module encapsulating hardening operations that otherwise require a
raw ``command``/``shell`` task.

A small number of remediations generated by the ComplianceAsCode project must
call a binary directly because no stock Ansible module provides the behavior:

* ``service auditd restart`` -- auditd sets ``RefuseManualStop=yes``, so the
  ``service``/``systemd`` modules cannot restart it.
* ``rpm -Va`` / ``rpm -qV`` / ``rpm -qf`` / ``rpm --restore`` /
  ``rpm --setperms`` / ``rpm --setugids`` -- the ``package`` module has no
  verify, query-owner or restore semantics.
* ``rpm --import`` -- the ``rpm_key`` module cannot import post-quantum (PQC)
  keys, so the key format introduced for RHEL requires ``rpm --import``.
* multiline RainerScript block/range removal from the rsyslog configuration --
  ``replace``/``lineinfile`` cannot delete a block conditionally on its content
  or a pattern range across a file glob.

This module exposes those behaviors as discrete, named operations so the
generated collection roles never shell out to ``command`` for them. It is
vendored into the collection at build time; the datastream and standalone
playbooks keep the original ``command`` tasks.
"""

from __future__ import absolute_import, division, print_function

__metaclass__ = type

DOCUMENTATION = r"""
---
module: ssg_hardening
short_description: Run ComplianceAsCode hardening operations without a raw command
description:
  - Encapsulates the handful of hardening steps that have no stock Ansible module
    equivalent (auditd restart, rpm verify/restore, rsyslog block/range removal)
    as discrete named operations.
options:
  operation:
    description: The hardening operation to perform.
    required: true
    type: str
    choices:
      - service_restart
      - rpm_verify_all
      - rpm_verify_package
      - rpm_query_file
      - rpm_restore
      - rpm_setperms
      - rpm_setugids
      - rpm_import
      - rsyslog_remove
  name:
    description:
      - Service name for C(service_restart), or package name for
        C(rpm_verify_package), C(rpm_setperms) and C(rpm_setugids).
    type: str
  path:
    description:
      - File path argument for C(rpm_query_file), C(rpm_restore) and
        C(rpm_import), or the single rsyslog file to edit for C(rsyslog_remove).
    type: str
  flags:
    description: Extra flags passed to C(rpm -Va) for C(rpm_verify_all).
    type: list
    elements: str
    default: []
  paths_glob:
    description:
      - Glob of rsyslog files to edit for C(rsyslog_remove) (e.g.
        C(/etc/rsyslog.d/*.conf)). Mutually exclusive with I(path).
    type: str
  mode:
    description: Removal mode for C(rsyslog_remove).
    type: str
    choices: [block, range]
  block_type:
    description:
      - RainerScript block keyword (e.g. C(action) or C(global)) for
        C(rsyslog_remove) when I(mode=block).
    type: str
  pattern:
    description:
      - Directive that must appear inside a block for it to be removed, for
        C(rsyslog_remove) when I(mode=block).
    type: str
  start:
    description:
      - Regex marking the first line of the range to delete, for
        C(rsyslog_remove) when I(mode=range).
    type: str
  end:
    description:
      - Regex marking the last line of the range to delete, for
        C(rsyslog_remove) when I(mode=range).
    type: str
author:
  - ComplianceAsCode project (@ComplianceAsCode)
"""

EXAMPLES = r"""
- name: Restart auditd
  ssg_hardening:
    operation: service_restart
    name: auditd

- name: Read files with incorrect permissions
  ssg_hardening:
    operation: rpm_verify_all
    flags:
      - --nodeps
      - --nosignature
  register: files_with_incorrect_permissions
  failed_when: files_with_incorrect_permissions.rc > 1

- name: Remove RainerScript action() entries with StreamDriverAuthMode
  ssg_hardening:
    operation: rsyslog_remove
    mode: block
    block_type: action
    pattern: StreamDriverAuthMode
    path: /etc/rsyslog.conf
"""

RETURN = r"""
rc:
  description: Return code of the underlying binary (0 for pure-Python operations).
  returned: always
  type: int
stdout:
  description: Standard output of the underlying binary.
  returned: for rpm/service operations
  type: str
stdout_lines:
  description: Standard output split into lines.
  returned: for rpm/service operations
  type: list
stderr:
  description: Standard error of the underlying binary.
  returned: for rpm/service operations
  type: str
files_changed:
  description: Files modified by C(rsyslog_remove).
  returned: for rsyslog_remove
  type: list
"""

import glob as globmod
import re

from ansible.module_utils.basic import AnsibleModule


# Operations that only read state: safe to run in check mode, never "changed",
# and a non-zero return code is left for the task's own failed_when to judge.
READ_ONLY_OPS = frozenset(("rpm_verify_all", "rpm_verify_package", "rpm_query_file"))

# POSIX character classes used by the sed programs these operations replace.
_POSIX_CLASSES = {
    "[[:space:]]": r"\s",
    "[[:alpha:]]": "[A-Za-z]",
    "[[:digit:]]": "[0-9]",
    "[[:alnum:]]": "[A-Za-z0-9]",
}


def _sed_to_py(pattern):
    """Translate the small subset of sed BRE used by the rsyslog removal
    macros into an equivalent Python regular expression.

    The macros only ever use POSIX classes plus literal parentheses, so we
    expand the classes and escape any unescaped ``(``/``)`` (literal in BRE
    but metacharacters in Python ``re``). No BRE capture groups are used."""
    for posix, repl in _POSIX_CLASSES.items():
        pattern = pattern.replace(posix, repl)
    out = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "\\" and i + 1 < len(pattern):
            out.append(pattern[i:i + 2])
            i += 2
            continue
        if c in "()":
            out.append("\\" + c)
        else:
            out.append(c)
        i += 1
    return "".join(out)


def _run(module, argv, read_only):
    """Run a binary, returning command-module-compatible facts."""
    bin_path = module.get_bin_path(argv[0], required=True)
    rc, out, err = module.run_command([bin_path] + argv[1:])
    result = dict(
        rc=rc,
        cmd=[bin_path] + argv[1:],
        stdout=out,
        stderr=err,
        stdout_lines=out.splitlines(),
        stderr_lines=err.splitlines(),
    )
    if not read_only and rc != 0:
        module.fail_json(msg="%s failed (rc=%d)" % (argv[0], rc), **result)
    return result


def _rsyslog_remove_range(lines, start_re, end_re):
    """Delete inclusive line ranges from a first match of start_re up to the
    next match of end_re, mirroring ``sed '/start/,/end/d'``."""
    out = []
    deleting = False
    for line in lines:
        if not deleting:
            if start_re.search(line):
                deleting = True
                # If start and end match the same line, delete just this line.
                if end_re.search(line):
                    deleting = False
                continue
            out.append(line)
        else:
            if end_re.search(line):
                deleting = False
            continue
    return out


def _rsyslog_remove_block(lines, open_re, pattern):
    """Delete a multiline ``block_type( ... )`` block when it contains pattern,
    mirroring the ``sed '/open/ { :a; N; /)/!ba; /pattern/d }'`` hold-space loop."""
    out = []
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        if open_re.search(line):
            block = [line]
            j = i
            while ")" not in lines[j] and j + 1 < n:
                j += 1
                block.append(lines[j])
            # block now spans i..j (inclusive of the line holding ")").
            if any(pattern in b for b in block):
                i = j + 1  # drop the whole block
                continue
            out.extend(block)
            i = j + 1
        else:
            out.append(line)
            i += 1
    return out


def _edit_file(module, filepath, transform):
    """Apply transform(lines) to a file; return True if it changed."""
    try:
        with open(filepath, "r") as f:
            original = f.read()
    except IOError:
        return False
    lines = original.splitlines(True)
    new_lines = transform(lines)
    new_content = "".join(new_lines)
    if new_content == original:
        return False
    if not module.check_mode:
        with open(filepath, "w") as f:
            f.write(new_content)
    return True


def _do_rsyslog_remove(module, p):
    if p["path"] and p["paths_glob"]:
        module.fail_json(msg="rsyslog_remove: path and paths_glob are mutually exclusive")
    if p["mode"] == "block":
        if not p["block_type"] or p["pattern"] is None:
            module.fail_json(msg="rsyslog_remove mode=block requires block_type and pattern")
        open_re = re.compile(r"^\s*" + re.escape(p["block_type"]) + r"\(")

        def transform(lines):
            return _rsyslog_remove_block(lines, open_re, p["pattern"])
    else:  # range
        if not p["start"] or not p["end"]:
            module.fail_json(msg="rsyslog_remove mode=range requires start and end")
        start_re = re.compile(_sed_to_py(p["start"]))
        end_re = re.compile(_sed_to_py(p["end"]))

        def transform(lines):
            return _rsyslog_remove_range(lines, start_re, end_re)

    targets = [p["path"]] if p["path"] else sorted(globmod.glob(p["paths_glob"]))
    changed_files = [t for t in targets if _edit_file(module, t, transform)]
    return dict(changed=bool(changed_files), rc=0, files_changed=changed_files)


def main():
    module = AnsibleModule(
        argument_spec=dict(
            operation=dict(
                type="str",
                required=True,
                choices=[
                    "service_restart",
                    "rpm_verify_all",
                    "rpm_verify_package",
                    "rpm_query_file",
                    "rpm_restore",
                    "rpm_setperms",
                    "rpm_setugids",
                    "rpm_import",
                    "rsyslog_remove",
                ],
            ),
            name=dict(type="str"),
            path=dict(type="str"),
            flags=dict(type="list", elements="str", default=[]),
            paths_glob=dict(type="str"),
            mode=dict(type="str", choices=["block", "range"]),
            block_type=dict(type="str"),
            pattern=dict(type="str"),
            start=dict(type="str"),
            end=dict(type="str"),
        ),
        required_if=[
            ("operation", "service_restart", ("name",)),
            ("operation", "rpm_verify_package", ("name",)),
            ("operation", "rpm_setperms", ("name",)),
            ("operation", "rpm_setugids", ("name",)),
            ("operation", "rpm_query_file", ("path",)),
            ("operation", "rpm_restore", ("path",)),
            ("operation", "rpm_import", ("path",)),
            ("operation", "rsyslog_remove", ("mode",)),
        ],
        supports_check_mode=True,
    )
    p = module.params
    op = p["operation"]

    if op == "rsyslog_remove":
        module.exit_json(**_do_rsyslog_remove(module, p))

    read_only = op in READ_ONLY_OPS

    if op == "service_restart":
        argv = ["service", p["name"], "restart"]
    elif op == "rpm_verify_all":
        argv = ["rpm", "-Va"] + list(p["flags"])
    elif op == "rpm_verify_package":
        argv = ["rpm", "-qV", p["name"]]
    elif op == "rpm_query_file":
        argv = ["rpm", "-qf", p["path"]]
    elif op == "rpm_restore":
        argv = ["rpm", "--restore", p["path"]]
    elif op == "rpm_setperms":
        argv = ["rpm", "--setperms", p["name"]]
    elif op == "rpm_setugids":
        argv = ["rpm", "--setugids", p["name"]]
    elif op == "rpm_import":
        argv = ["rpm", "--import", p["path"]]
    else:  # pragma: no cover - guarded by choices
        module.fail_json(msg="unsupported operation %s" % op)

    # State-changing operations are no-ops in check mode.
    if not read_only and module.check_mode:
        module.exit_json(changed=True, rc=0, cmd=argv)

    result = _run(module, argv, read_only)
    result["changed"] = not read_only
    module.exit_json(**result)


if __name__ == "__main__":
    main()
