---
# platform = multi_platform_fedora,multi_platform_rhel,multi_platform_rhcos
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
    machineconfiguration.openshift.io/role: worker
  name: 75-banner-etc-issue
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,{{.login_banner_contents | unescapeNewlines | urlencode}}
        mode: 0644
        path: /etc/issue.d/legal-notice
        overwrite: true
