---
# platform = multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
spec:
  kubeletConfig:
    evictionSoft:
      nodefs.inodesFree: {{.var_kubelet_evictionsoft_nodefs_inodesfree}}
    evictionSoftGracePeriod:
      nodefs.inodesFree: "1m30s"
    evictionPressureTransitionPeriod: 0s
