---
# platform = multi_platform_ocp
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
spec:
  kubeletConfig:
    evictionSoft:
      imagefs.inodesFree: {{.var_kubelet_evictionsoft_imagefs_inodesfree}}
    evictionSoftGracePeriod:
      imagefs.inodesFree: "1m30s"
    evictionPressureTransitionPeriod: 0s
