# platform = multi_platform_almalinux,multi_platform_fedora,multi_platform_ol,multi_platform_opensuse,multi_platform_rhel
# reboot = false
# strategy = unknown
# complexity = low
# disruption = medium
- name: "Prevent user modification of GNOME Screensaver lock-enabled"
  ansible.builtin.lineinfile:
    {{% if product in ['opensuse16', 'sle15', 'sle16'] %}}
    path: /etc/dconf/db/{{{ dconf_gdm_dir }}}/locks/00-security-settings-lock
    {{% else %}}
    path: /etc/dconf/db/local.d/locks/00-security-settings-lock
    {{% endif %}}
    regexp: '^/org/gnome/desktop/screensaver/lock-enabled$'
    line: '/org/gnome/desktop/screensaver/lock-enabled'
    create: yes
    mode: 0644
  register: result_lineinfile

{{% if product in ['opensuse16', 'sle15', 'sle16'] %}}
{{{ ansible_enable_dconf_user_profile(profile="gdm", database="gdm") }}}
{{% endif %}}

- name: Dconf Update
  ansible.builtin.command: dconf update
  when: result_lineinfile is changed
