documentation_complete: true
title: 'NIST SP 800-53 Rev 5'
description: |-
    Contains all rules mapped to NIST SP 800-53 Revision 5 controls in
    ComplianceAsCode for Fedora, across all baselines (Low, Moderate, High).

    Generated by utils/nist_sync/export_to_gemara.py. Do not edit manually.
selections:
    - nist_800_53:all
