name: Merge Commit Check

on:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-no-merges-${{ github.event.number || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: read

jobs:
    validate-merge-commits:
        name: Ensure No Merge Commits
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
            -   name: Check for Merge Commits
                uses: NexusPHP/no-merge-commits@12c2e2b73188012fd2b353ab5cbd9bb15159ef02 # v2.3.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
