name: Merge Commit Check

on:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-no-merges-${{ github.event.number || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read
    pull-requests: read

jobs:
    validate-merge-commits:
        name: Ensure No Merge Commits
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
            -   name: Check for Merge Commits
                uses: NexusPHP/no-merge-commits@109a3342781ddcf26b2fa739f29e8ee9f68b7d8e # v2.4.1
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
